# Q-Learning Maze Robot Configuration
experiment:
  name: "q_learning_maze_robot"
  log_level: "INFO"

# Q-Learning Agent Parameters
agent:
  learning_rate: 0.12
  min_learning_rate: 0.01
  lr_decay: 0.997
  discount_factor: 0.96

# Exploration Strategy Configuration
# Options: epsilon_greedy, ucb, curiosity
strategy:
  name: "curiosity"
  epsilon: 0.6
  epsilon_decay: 0.999
  epsilon_min: 0.15
  ucb_factor: 2.0
  novelty_bonus: 5.0               

# Reward Structure
rewards:
  collision: -12.0                 
  goal_reached: 1000.0           
  exploration_bonus: 30.0
  loop_penalty: -14.0

# Environment Configuration
environment:
  max_steps: 200         
  min_steps: 100
  collision_limit: 15
  loop_threshold: 18

  checkpoint:
    base_bonus: 100.0
    progressive_multiplier: 25.0
    stagnation_threshold: 20
    stagnation_penalty: -3.0

# Training Configuration
training:
  episodes: 250
  save_every: 10
  test_episodes: 8
  model_path: "models/q_agent.pkl"