# Q-Learning Maze Robot Configuration
experiment:
  name: "q_learning_maze_robot"
  log_level: "INFO"

# Q-Learning Agent Parameters
agent:
  learning_rate: 0.15
  min_learning_rate: 0.03
  lr_decay: 0.9995
  discount_factor: 0.98

# Exploration Strategy Configuration
strategy:
  name: "curiosity"
  epsilon: 0.7
  novelty_bonus: 8.0        

# Reward Structure
rewards:
  collision: -15.0                 
  goal_reached: 1000.0           
  loop_penalty: -15.0

# Environment Configuration
environment:
  steps: 150

  checkpoint:
    base_bonus: 100.0

# Training Configuration
training:
  episodes: 10000
  save_every: 50
  test_episodes: 10
  model_path: "models/q_agent.pkl"