# Q-Learning Maze Robot Configuration
experiment:
  name: "q_learning_maze_robot"
  log_level: "INFO"

# Q-Learning Agent Parameters
agent:
  learning_rate: 0.12
  min_learning_rate: 0.02
  lr_decay: 0.997
  discount_factor: 0.96

# Exploration Strategy Configuration
strategy:
  name: "curiosity"
  epsilon: 0.3
  novelty_bonus: 8.0

# Reward Structure
rewards:
  collision: -13.0                 
  goal_reached: 1000.0           
  loop_penalty: -13.0

# Environment Configuration
environment:
  steps: 225

  checkpoint:
    base_bonus: 100.0

# Training Configuration
training:
  episodes: 10000
  save_every: 10
  model_path: "models/q_agent.pkl"

test_episodes: 10